# Site/SEO settings
email: info@kinlane.com
baseurl: http://the.us.narrative.today.kinlane.com
paginate: 30
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: The US Narrative Today
title: The US Narrative Today
description: >
  The narrative across the United States today, pulling news stories from all 50 states, and assembling them into a single narrative for the day.
url: http://the.us.narrative.today.kinlane.com
twitter_username: kinlane
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/kinlane
  - name: instagram
    url: https://www.instagram.com/kinlane/
  - name: linkedin
    url: https://www.linkedin.com/in/kinlane/
  - name: github
    url: https://github.com/kinlane

# Author settings
author:
  - name: Kin Lane
    bio: I am a writer, photographer, storyteller, and recovering technologist.
    url: http://kinlane.com

# Build settings
markdown: kramdown
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
